server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/socialapp
    username: root
    password: rnrdj123


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true



jwt:
  secret:
    key: halo3030993


logging:
  level:
    com.example.socialApi: debug
