server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/socialapp
    username: root
    password: rnrdj123
  servlet:
    multipart:
      max-request-size: 10MB
      enabled: true
      max-file-size: 10MB
      location: C:\\Users\\SUN\\work\\socialapp\\ui\\public\\upload

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true



jwt:
  secret:
    key: halo3030993


logging:
  level:
    com.example.socialApi: debug

com.example.socialapp.path: C:\\Users\\SUN\\work\\socialapp\\ui\\public\\upload

